version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: iis_db
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html/
    environment:
      DATABASE_URL: "mysql://newuser:password@db/iis_db" 

volumes:
  db_data: {}