#!/bin/sh
set -o posix
usage() { 
echo "Usage: $0 [-h] [-abgsdrh] [COMMAND] [LOG [LOG2 [...]]]
-a DATETIME — after: jsou uvažovány pouze záznamy PO tomto datu (včetně tohoto data). DATETIME je formátu YYYY-MM-DD
-b DATETIME — before: jsou uvažovány pouze záznamy PŘED tímto datem (včetně tohoto data)
-g GENDER : jsou uvažovány pouze záznamy nakažených osob daného pohlaví. GENDER může být M (muži) nebo Z (ženy)
-s [WIDTH] : u příkazů gender, age, daily, monthly, yearly, countries, districts a regions vypisuje data ne číselně, 
             ale graficky v podobě histogramů. Nepovinný parametr WIDTH nastavuje šířku histogramů, tedy délku nejdelšího řádku, 
             na WIDTH. Tedy, WIDTH musí být kladné celé číslo. Pokud není parametr WIDTH uveden, řídí se šířky řádků požadavky 
             uvedenými níže
-d DISTRICT_FILE — pro příkaz districts vypisuje místo LAU 1 kódu okresu jeho jméno. Mapování kódů na jména je v souboru DISTRICT_FILE
-r REGIONS_FILE — pro příkaz regions vypisuje místo NUTS 3 kódu kraje jeho jméno. Mapování kódů na jména je v souboru REGIONS_FILE
-h — vypíše nápovědu s krátkým popisem každého příkazu a přepínače

COMMAND může být jeden z:
infected — spočítá počet nakažených
merge — sloučí několik souborů se záznamy do jednoho, zachovávající původní pořadí (hlavička bude ve výstupu jen jednou)
gender — vypíše počet nakažených pro jednotlivá pohlaví
age — vypíše statistiku počtu nakažených osob dle věku (bližší popis je níže)
daily — vypíše statistiku nakažených osob pro jednotlivé dny
monthly — vypíše statistiku nakažených osob pro jednotlivé měsíce
yearly — vypíše statistiku nakažených osob pro jednotlivé roky
countries — vypíše statistiku nakažených osob pro jednotlivé země nákazy (bez ČR, tj. kódu CZ)
districts — vypíše statistiku nakažených osob pro jednotlivé okresy
regions — vypíše statistiku nakažených osob pro jednotlivé kraje
"; exit 0; 
}

checkarg () {
if ! [[ $OPTARG =~ ^[0-9]+$ ]]
then
    OPTIND=$(( OPTIND - 1 ))
    s_arg=default
else
    s_arg="$OPTARG"
fi
}

header="id,datum,vek,pohlavi,kraj_nuts_kod,okres_lau_kod,nakaza_v_zahranici,nakaza_zeme_csu_kod,reportovano_khs"

a_flag=0
a_arg=
b_flag=0
b_arg=
g_flag=0
g_arg=
s_flag=0
s_arg=
d_flag=0
d_arg=
r_flag=0
r_arg=
z_flag=1

command=
l_z_flag=1 #logs zero flag

input=

while getopts "a:b:g:s:d:r:h" arg;
do
    case "${arg}" in
        h)
            usage
            exit 0
            ;;
        a)
            a_flag=1
            a_arg="$OPTARG"
            z_flag=0
            ;;
        b)
            b_flag=1
            b_arg="$OPTARG"
            z_flag=0
            ;;
        g)
            g_flag=1
            g_arg="$OPTARG"
            z_flag=0
            ;;
        s)
            s_flag=1
            checkarg
            z_flag=0
            ;;
        d)
            d_flag=1
            d_arg="$OPTARG"
            z_flag=0
            ;;
        r)
            r_flag=1
            r_arg="$OPTARG"
            z_flag=0
            ;;

        *)
            echo "Wrong argument!"
            ;;
    esac
done

shift $(( OPTIND - 1 ))
IFS=$(printf '\n')
while [ $# -gt 0 ]
do
    case "$1" in
        *.csv)
            in=$(cat ${1})
            input+=${in}
            input+=$'\n'
            if [ -n $l_z_flag ]
            then
                l_z_flag=0
            fi
            shift
            ;;
        *.gz)
            in=$(gzip -cd ${1})
            input+=${in}
            input+=$'\n'
            if [ $l_z_flag -ne 0 ]
            then
                l_z_flag=0
            fi
            shift
            ;;
        *.bz2)
            in=$(bzip2 -cd ${1})
            input+=${in}
            input+=$'\n'
            if [ $l_z_flag -ne 0 ]
            then
                l_z_flag=0
            fi
            shift
            ;;
        *)
            if [ -z $command ]
            then
                if [ $l_z_flag -eq 0 ]
                then
                    echo "Wrong sequence of arguments!" >&2
                    exit 1
                fi
                command=$1
                shift
                z_flag=0
            else
                echo "Wrong argument : $1!" >&2
                exit 1
            fi
            ;;
        esac
done

if [ $l_z_flag -eq 1 ]
then
    first_byte=$(dd bs=1 count=1 2>/dev/null | od -t o1 -A n | tr -dc 0-9)
    if [ -z "$first_byte" ]
    then
        echo $header
        exit 0
    fi
    input+="$(< /dev/stdin)"
    input+=$'\n'
fi

h_c=1
echo $input | awk -F ',' \
-v a_f="$a_flag" \
-v a_a="$a_arg" \
-v b_f="$b_flag" \
-v b_a="$b_arg" \
-v g_f="$g_flag" \
-v g_a="$g_arg" \
-v s_f="$s_flag" \
-v s_a="$s_arg" \
-v header="$header" \
-v command="$command" \
'function s_det() {
    if (s_a == "default") {
        if (command == "gender") {
            max=100000
        } else if (command == "age") {
            max=10000
        } else if (command == "daily") {
            max=500
        } else if (command == "monthly") {
            max=10000
        } else if (command == "yearly") {
            max=100000
        } else if (command == "countries") {
            max=100
        } else if (command == "districts") {
            max=1000
        } else if (command == "regions") {
            max=10000
        }
    } else {
        max=max/s_a
        if (s_a == 27) max=max-1
    }
}
BEGIN { 
    header_c=1
    err_c=0
    date_c=0
    dates_s=""
    if (command == "age") {
        dates[0] = "0-5"
        dates[1] = "6-15"
        dates[2] = "16-25"
        dates[3] = "26-35"
        dates[4] = "36-45"
        dates[5] = "46-55"
        dates[6] = "56-65"
        dates[7] = "66-75"
        dates[8] = "76-85"
        dates[9] = "86-95"
        dates[10] = "96-105"
        dates[11] = ">105"
        dates[12] = "None"
        date_c=13

        for (i=0; i < 13; i++) {
            dates_c[dates[i]] = 0
        }

    }
    } {
    check=1
    orig=$0
    gsub(" ", "")

    if ($0 ~ header || $0 ~ /^[[:space:]]*$/) {
    } else {
        if ($3 ~ /^[0-9]+$/ || length($3) == 0) {
        } else {
            err[err_c]="Invalid age: " orig
            err_c++
            check=0
        }
        if ($2 ~ /^[0-9]{4}-[0-9]{2}-[0-9]{2}$/ || length($2) == 0) {
            if (length($2) == 0) {
            } else {
                month=substr($2, 6, 2)
                day=substr($2, 9, 2)
                if (day > "31" || day < "01") {
                    err[err_c]="Invalid date: " orig
                    err_c++
                    check=0
                } else if (month > "12" || month < "01") {
                    err[err_c]="Invalid date: " orig
                    err_c++
                    check=0
                } else if (month == "02") {
                    if (day > "29") {
                        err[err_c]="Invalid date: " orig
                        err_c++
                        check=0
                    }
                }
            }
        } else {
            err[err_c]="Invalid date: " orig
            err_c++
            check=0
        }

        if (check) {
            if (a_f) {
                if (a_a > $2) {
                    check = 0
                }
            }
            if (b_f) {
                if (b_a < $2) {
                    check = 0
                }
            }
            if (g_f) {
                if (g_a != $4) {
                    check = 0
                }
            }
            if (check) {
                if (command == "infected") {
                    inf++;
                }
                if (command == "merge" || length(command) == 0) {
                    if (header_c) {
                        print header
                        header_c--
                    }
                    print $0
                }
                if (command == "gender") {
                    if ($4 == "M") {
                        M++
                        if (M > max) {
                            max=M
                        }
                    } else if ($4 == "Z") {
                        Z++
                        if (Z > max) {
                            max=Z
                        }
                    } else {
                        None++
                        if (None > max) {
                            max=None
                        }
                    }
                }
                if (command == "age") {
                    if ($3 >= 0 && $3 < 6) {
                        dates_c[dates[0]]++
                        if (dates_c[dates[0]] > max) {
                            max=dates_c[dates[0]]
                        }
                    } else if ($3 > 5 && $3 < 16) {
                        dates_c[dates[1]]++
                        if (dates_c[dates[1]] > max) {
                            max=dates_c[dates[1]]
                        }
                    } else if ($3 > 15 && $3 < 26) {
                        dates_c[dates[2]]++
                        if (dates_c[dates[2]] > max) {
                            max=dates_c[dates[2]]
                        }
                    } else if ($3 > 25 && $3 < 36) {
                        dates_c[dates[3]]++
                        if (dates_c[dates[3]] > max) {
                            max=dates_c[dates[3]]
                        }
                    } else if ($3 > 35 && $3 < 46) {
                        dates_c[dates[4]]++
                        if (dates_c[dates[4]] > max) {
                            max=dates_c[dates[4]]
                        }
                    } else if ($3 > 45 && $3 < 56) {
                        dates_c[dates[5]]++
                        if (dates_c[dates[5]] > max) {
                            max=dates_c[dates[5]]
                        }
                    } else if ($3 > 55 && $3 < 66) {
                        dates_c[dates[6]]++
                        if (dates_c[dates[6]] > max) {
                            max=dates_c[dates[6]]
                        }
                    } else if ($3 > 65 && $3 < 76) {
                        dates_c[dates[7]]++
                        if (dates_c[dates[7]] > max) {
                            max=dates_c[dates[7]]
                        }
                    } else if ($3 > 75 && $3 < 86) {
                        dates_c[dates[8]]++
                        if (dates_c[dates[8]] > max) {
                            max=dates_c[dates[8]]
                        }
                    } else if ($3 > 85 && $3 < 96) {
                        dates_c[dates[9]]++
                        if (dates_c[dates[9]] > max) {
                            max=dates_c[dates[9]]
                        }
                    } else if ($3 > 95 && $3 < 106) {
                        dates_c[dates[10]]++
                        if (dates_c[dates[10]] > max) {
                            max=dates_c[dates[10]]
                        }
                    } else if ($3 > 105) {
                        dates_c[dates[11]]++
                        if (dates_c[dates[11]] > max) {
                            max=dates_c[dates[11]]
                        }
                    } else {
                        dates_c[dates[12]]++
                        if (dates_c[dates[12]] > max) {
                            max=dates_c[dates[12]]
                        }
                    }
                }
                if (command == "daily") {
                    if (length($2) == 0) {
                        dates_c[None]++
                        if (dates_c[None] > max) {
                            max=dates_c[None]
                        }
                    } else {
                        if (index(dates_s, $2) != 0) {
                            dates_c[$2]++
                            if (dates_c[$2] > max) {
                                max=dates_c[$2]
                            }
                        } else {
                            buffi=$2
                            dates_s=dates_s " " buffi
                            dates_c[$2]++
                            if (dates_c[$2] > max) {
                                max=dates_c[$2]
                            }
                            dates[date_c]=$2
                            date_c++
                        }
                    }
                }
                if (command == "monthly") {
                    if (length($2) == 0) {
                        dates_c[None]++
                        if (dates_c[None] > max) {
                            max=dates_c[None]
                        }
                    } else {
                        month=substr($2, 1, 7)
                        if (index(dates_s, month) != 0) {
                            dates_c[month]++
                            if (dates_c[month] > max) {
                                max=dates_c[month]
                            }
                        } else {
                            dates_s=dates_s " " month
                            dates_c[month]++
                            if (dates_c[month] > max) {
                                max=dates_c[month]
                            }
                            dates[date_c]=month
                            date_c++
                        }
                    }
                }
                if (command == "yearly") {
                    if (length($2) == 0) {
                        dates_c[None]++
                        if (dates_c[None] > max) {
                            max=dates_c[None]
                        }
                    } else {
                        year=substr($2, 1, 4)
                        if (index(dates_s, year) != 0) {
                            dates_c[year]++
                            if (dates_c[year] > max) {
                                max=dates_c[year]
                            }
                        } else {
                            dates_s=dates_s " " year
                            dates_c[year]++
                            if (dates_c[year] > max) {
                                max=dates_c[year]
                            }
                            dates[date_c]=year
                            date_c++
                        }
                    }
                }
                if (command == "countries") {
                    if ($8 !~ "CZ") {
                        if (index(dates_s, $8) != 0) {
                            dates_c[$8]++
                            if (dates_c[$8] > max) {
                                max=dates_c[$8]
                            }
                        } else {
                            buffi=$8
                            dates_s=dates_s " " $8
                            dates_c[$8]++
                            if (dates_c[$8] > max) {
                                max=dates_c[$8]
                            }
                            dates[date_c]=$8
                            date_c++
                        }
                    }
                }
                if (command == "districts") {
                    if (length($6) == 0) {
                        dates_c[None]++
                        if (dates_c[None] > max) {
                            max=dates_c[None]
                        }
                    } else {
                        if (index(dates_s, $6) != 0) {
                            dates_c[$6]++
                            if (dates_c[$6] > max) {
                                max=dates_c[$6]
                            }
                        } else {
                            buffi=$6
                            dates_s=dates_s " " $6
                            dates_c[$6]++
                            if (dates_c[$6] > max) {
                                max=dates_c[$6]
                            }
                            dates[date_c]=$6
                            date_c++
                        }
                    }
                }
                if (command == "regions") {
                    if (length($5) == 0) {
                        dates_c[None]++
                        if (dates_c[None] > max) {
                            max=dates_c[None]
                        }
                    } else {
                        if (index(dates_s, $5) != 0) {
                            dates_c[$5]++
                            if (dates_c[$5] > max) {
                                max=dates_c[$5]
                            }
                        } else {
                            buffi=$5
                            dates_s=dates_s " " $5
                            dates_c[$5]++
                            if (dates_c[$5] > max) {
                                max=dates_c[$5]
                            }
                            dates[date_c]=$5
                            date_c++
                        }
                    }
                }
            }
        }
    }
} END {
    if (s_f) s_det()
    if (command == "infected") {
        print inf
    }
    if (command == "gender") {
        if (s_f) {
            m=M
            z=Z
            n=None
            M=""
            Z=""
            None=""
            for (i=0; i < int(m/max); i++) {
                M=M "#"
            }
            for (i=0; i < int(z/max); i++) {
                Z=Z "#"
            }
            for (i=0; i < int(n/max); i++) {
                None=None "#"
            }
        }
        print "M: " M
        print "Z: " Z
        if (None) {
            print "None: " None
        }
    }
    if (s_f && index("age daily monthly yearly countries districts regions", command) != 0) {
        for (i=0; i < date_c; i++) {
            buf[i] = dates_c[dates[i]]
            dates_c[dates[i]]=""
            for (j=0; j < int(buf[i]/max); j++) {
                dates_c[dates[i]]=dates_c[dates[i]] "#"
            }
        }
        if (dates_c[None]) {
            buf[None] = dates_c[None]
            dates_c[None]=""
            for (j=0; j < int(buf[None]/max); j++) {
                dates_c[None]=dates_c[None] "#"
            }
        }
    }
    if (command == "age") {
        print "0-5   : " dates_c[dates[0]]
        print "6-15  : " dates_c[dates[1]]
        print "16-25 : " dates_c[dates[2]]
        print "26-35 : " dates_c[dates[3]]
        print "36-45 : " dates_c[dates[4]]
        print "46-55 : " dates_c[dates[5]]
        print "56-65 : " dates_c[dates[6]]
        print "66-75 : " dates_c[dates[7]]
        print "76-85 : " dates_c[dates[8]]
        print "86-95 : " dates_c[dates[9]]
        print "96-105: " dates_c[dates[10]]
        print ">105  : " dates_c[dates[11]]
        if (dates_c[dates[12]]) {
            print "None  : " dates_c[dates[12]]
        }
    }
    if (command == "daily" || command == "monthly" || command == "yearly") {
        for (i=0; i < date_c; i++) {
            print dates[i] ": " dates_c[dates[i]]
        }
        if (dates_c[None]) {
            print "None: " dates_c[None]
        }
    }
    if (command == "countries" || command == "districts" || command == "regions") {
        date_c_b=date_c-1
        while (date_c_b != 0) {
            for(i=0; i < date_c_b; i++) {
                if (dates[i] > dates[i+1]) {
                    t = dates[i]
                    dates[i] = dates[i+1]
                    dates[i+1] = t
                }
            }
            date_c_b--
        }
        for(i=0; i < date_c; i++) {
            print dates[i] ": " dates_c[dates[i]]
        }
        if (command == "countries") {
            dates_c[None]=0
        }
        if (dates_c[None]) {
            print "None: " dates_c[None]
        }
    }
    if (err_c) {
        for (i=0; i < err_c; i++) {
            print err[i] >"/dev/stderr"
        }
    }
}'

exit 0
